"""Build the answer key: NHTSA complaints with the components NHTSA recorded for them.

Reads the complaint files in data/raw/ (run download_data.py first), groups rows into
complaints, cleans the labels, and splits by the date NHTSA received each complaint:
train (before 2024), dev (2024), test (2025 onward). Writes:
  data/processed/{train,dev,test}.jsonl   full splits (not committed)
  data/processed/manifest.json            sources, checksums, and counts
  data/sample/test_sample.jsonl           a fixed 1,000-complaint test sample (committed)
  docs/answer-key.md                      a readable summary of the above

    python scripts/build_answer_key.py

NHTSA updates its files in place, so a later download usually differs from the files the published
answer key was built from (carsafety.complaints.PUBLISHED_SOURCES). The script then stops before writing
anything, so the published answer key and test sample, and every score measured on them, stay as they
are. --replace-published builds from the new download anyway.
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

from carsafety.complaints import changed_sources, read_rows, sha256, split_by_date, to_complaints
from carsafety.privacy import scrub

ROOT = Path(__file__).resolve().parent.parent
RAW, PROCESSED, SAMPLE = ROOT / "data" / "raw", ROOT / "data" / "processed", ROOT / "data" / "sample"
SOURCES = ["COMPLAINTS_RECEIVED_2015-2019", "COMPLAINTS_RECEIVED_2020-2024", "COMPLAINTS_RECEIVED_2025-2026"]
SAMPLE_SIZE, SAMPLE_SEED = 1000, 2026
COLUMNS = ["id", "received", "make", "model", "model_year", "crash", "fire", "injured", "deaths", "text", "labels"]


def write_jsonl(frame, path: Path, clean_text: bool = False) -> None:
    with path.open("w", encoding="utf-8") as out:
        for record in frame[COLUMNS].to_dict(orient="records"):
            if clean_text:
                record["text"] = scrub(record["text"])
            out.write(json.dumps(record, ensure_ascii=False) + "\n")


STOP = """These files in {raw} aren't the ones the published answer key was built from: {files}.
NHTSA updates its files in place, so a new download usually differs. Nothing was written: the published
answer key (docs/answer-key.md) and test sample (data/sample/test_sample.jsonl) stay as they are, so every
published score can still be checked against them. To build from these files anyway, which replaces both
and changes the scores a little, run: python scripts/build_answer_key.py --replace-published"""


def main(argv: list[str] | None = None) -> None:
    global RAW
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--raw", type=Path, default=RAW, help="the folder with NHTSA's files (default: data/raw)")
    parser.add_argument("--replace-published", action="store_true",
                        help="build from files that differ from the published ones, replacing the published answer key")
    args = parser.parse_args(argv)
    RAW = args.raw
    changed = changed_sources(RAW)
    if changed and not args.replace_published:
        raise SystemExit(STOP.format(raw=RAW, files=", ".join(changed)))
    PROCESSED.mkdir(parents=True, exist_ok=True)
    SAMPLE.mkdir(parents=True, exist_ok=True)
    rows = read_rows(RAW / f"{name}.txt" for name in SOURCES)
    complaints = to_complaints(rows)
    splits = split_by_date(complaints)
    for name, frame in splits.items():
        write_jsonl(frame, PROCESSED / f"{name}.jsonl")
    sample = splits["test"].sample(n=SAMPLE_SIZE, random_state=SAMPLE_SEED).sort_values("id")
    write_jsonl(sample, SAMPLE / "test_sample.jsonl", clean_text=True)

    label_counts = {name: Counter(l for ls in frame.labels for l in ls) for name, frame in splits.items()}
    manifest = {
        "sources": {f"{name}.zip": sha256(RAW / f"{name}.zip") for name in SOURCES},
        "vehicle_rows": len(rows),
        "complaints": len(complaints),
        "complaints_without_known_component": int((complaints.labels.str.len() == 0).sum()),
        "splits": {name: {"complaints": len(frame), "received_from": frame.received.min(), "received_to": frame.received.max()}
                   for name, frame in splits.items()},
        "labels": sorted(set().union(*label_counts.values())),
        "test_sample": {"size": SAMPLE_SIZE, "seed": SAMPLE_SEED},
    }
    (PROCESSED / "manifest.json").write_text(json.dumps(manifest, indent=2))

    lines = ["# Answer key", "", "Generated by `scripts/build_answer_key.py`. Don't edit by hand.", "",
             "## Sources (NHTSA, downloaded from static.nhtsa.gov)", "", "| File | SHA-256 |", "|---|---|"]
    lines += [f"| {f} | `{h}` |" for f, h in manifest["sources"].items()]
    lines += ["", "## What's in it", "",
              f"- Vehicle complaint rows read: {manifest['vehicle_rows']:,}",
              f"- Complaints after grouping rows: {manifest['complaints']:,}",
              f"- Left out because no known component was recorded: {manifest['complaints_without_known_component']:,}",
              "", "| Split | Complaints | Received from | Received to |", "|---|---|---|---|"]
    lines += [f"| {n} | {s['complaints']:,} | {s['received_from']} | {s['received_to']} |" for n, s in manifest["splits"].items()]
    lines += ["", f"Fixed test sample: {SAMPLE_SIZE:,} complaints from the test split (seed {SAMPLE_SEED}), in `data/sample/test_sample.jsonl`.",
              "", f"## Labels ({len(manifest['labels'])}), share of complaints that have each", "",
              "| Label | Train | Dev | Test |", "|---|---|---|---|"]
    by_test = sorted(manifest["labels"], key=lambda l: -label_counts["test"][l])
    for label in by_test:
        cells = [f"{label_counts[n][label] / len(splits[n]):.1%}" for n in ("train", "dev", "test")]
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
    (ROOT / "docs" / "answer-key.md").write_text("\n".join(lines) + "\n")
    print(json.dumps({k: v for k, v in manifest.items() if k != "labels"}, indent=2))
    print(f"labels: {len(manifest['labels'])}")


if __name__ == "__main__":
    main()
