"""Score two simple baselines that the AI has to beat.

1. Most common label: predict the single most frequent component for every complaint.
2. Keyword model: TF-IDF word features plus one logistic-regression classifier per label,
   with the decision threshold tuned on the dev split. A strong, classic, non-AI baseline.

Scores both on the full test split and on the fixed 1,000-complaint sample, then writes
docs/results/baselines.md and data/processed/baselines.json.

    python scripts/run_baselines.py
"""
from __future__ import annotations

import json
import platform
import time
from collections import Counter
from pathlib import Path

import numpy as np
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import MultiLabelBinarizer

from carsafety.metrics import score

ROOT = Path(__file__).resolve().parent.parent
PROCESSED = ROOT / "data" / "processed"
TRAIN_SAMPLE, SEED = 200_000, 2026


def load(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as f:
        return [json.loads(line) for line in f]


def predict_sets(probabilities: np.ndarray, classes, threshold: float) -> list[set[str]]:
    """Labels above the threshold; if none, the single most likely label (every complaint has one)."""
    out = []
    for row in probabilities:
        chosen = {classes[i] for i in np.flatnonzero(row >= threshold)}
        out.append(chosen or {classes[int(row.argmax())]})
    return out


def main() -> None:
    train, dev, test = (load(PROCESSED / f"{n}.jsonl") for n in ("train", "dev", "test"))
    sample = load(ROOT / "data" / "sample" / "test_sample.jsonl")
    rng = np.random.default_rng(SEED)
    train = [train[i] for i in rng.choice(len(train), size=min(TRAIN_SAMPLE, len(train)), replace=False)]
    results = {}

    common = Counter(l for r in train for l in r["labels"]).most_common(1)[0][0]
    results["Most common label"] = {name: score([r["labels"] for r in data], [{common}] * len(data))
                                    for name, data in (("test", test), ("sample", sample))}

    started = time.time()
    binarizer = MultiLabelBinarizer()
    y_train = binarizer.fit_transform([r["labels"] for r in train])
    vectorizer = TfidfVectorizer(ngram_range=(1, 2), min_df=5, max_features=300_000, sublinear_tf=True, strip_accents="unicode")
    x_train = vectorizer.fit_transform(r["text"] for r in train)
    x_train.sort_indices()  # sort once here: the parallel workers get read-only copies and can't sort them
    model =OneVsRestClassifier(LogisticRegression(max_iter=1000, solver="liblinear"), n_jobs=-1).fit(x_train, y_train)
    classes = list(binarizer.classes_)
    dev_probs = model.predict_proba(vectorizer.transform(r["text"] for r in dev))
    thresholds = [round(t, 2) for t in np.arange(0.15, 0.61, 0.05)]
    dev_f1 = {t: score([r["labels"] for r in dev], predict_sets(dev_probs, classes, t))["micro_f1"] for t in thresholds}
    best = max(dev_f1, key=dev_f1.get)
    results["Keyword model (TF-IDF + logistic regression)"] = {
        name: score([r["labels"] for r in data], predict_sets(model.predict_proba(vectorizer.transform(r["text"] for r in data)), classes, best))
        for name, data in (("test", test), ("sample", sample))
    }
    seconds = time.time() - started
    # Save the keyword model's answers on the fixed sample, so later steps can compare per complaint.
    (PROCESSED / "predictions").mkdir(exist_ok=True)
    sample_sets = predict_sets(model.predict_proba(vectorizer.transform(r["text"] for r in sample)), classes, best)
    with (PROCESSED / "predictions" / "test-keyword.jsonl").open("w", encoding="utf-8") as out:
        for r, labels in zip(sample, sample_sets):
            out.write(json.dumps({"id": r["id"], "labels": sorted(labels)}) + "\n")

    def row(name, s):
        return f"| {name} | {s['micro_precision']:.3f} | {s['micro_recall']:.3f} | **{s['micro_f1']:.3f}** | {s['macro_f1']:.3f} | {s['exact_match']:.3f} |"

    lines = ["# Baseline results", "", "Generated by `scripts/run_baselines.py`. Don't edit by hand.", "",
             f"Train: {len(train):,} complaints sampled from the train split (seed {SEED}). "
             f"The decision threshold ({best}) was chosen on the dev split ({len(dev):,} complaints).", ""]
    for split, title in (("test", f"Full test split ({len(test):,} complaints received from 2025 onward)"),
                         ("sample", f"Fixed test sample ({len(sample):,} complaints, the set the AI will be scored on)")):
        lines += [f"## {title}", "", "| Baseline | Micro precision | Micro recall | Micro F1 | Macro F1 | Exact match |", "|---|---|---|---|---|---|"]
        lines += [row(name, r[split]) for name, r in results.items()] + [""]
    keyword = results["Keyword model (TF-IDF + logistic regression)"]["test"]
    lines += ["## Keyword model, per label (full test split)", "", "| Label | Precision | Recall | F1 | Complaints |", "|---|---|---|---|---|"]
    lines += [f"| {s.label} | {s.precision:.3f} | {s.recall:.3f} | {s.f1:.3f} | {s.support:,} |"
              for s in sorted(keyword["per_label"], key=lambda s: -s.support) if s.support]
    lines += ["", f"Environment: Python {platform.python_version()}, scikit-learn {sklearn.__version__}. "
              f"Keyword model training and scoring took {seconds:.0f} seconds."]
    (ROOT / "docs" / "results").mkdir(parents=True, exist_ok=True)
    (ROOT / "docs" / "results" / "baselines.md").write_text("\n".join(lines) + "\n")
    summary = {name: {split: {k: v for k, v in s.items() if k != "per_label"} for split, s in r.items()} for name, r in results.items()}
    summary["threshold"], summary["dev_micro_f1_by_threshold"] = best, dev_f1
    (PROCESSED / "baselines.json").write_text(json.dumps(summary, indent=2))
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
